### ISSUE TITLE
WIP: I rewrote most of the core syntax rules

### ISSUE THREAD

**Issue by azizk** [princemaple/elixir-sublime-syntax#10]
Hi there!

Hope all is well. I've been working like crazy on improving the syntax highlighting file. I think it's almost ready to be released, but I thought I'd let you know in advance so you can check it out for yourself. There are an incredible amount of changes and improvements I made. Some of which are:

- Parameter highlighting (in fn blocks it's only for the first -> clause)
- Binary string << >> matching that handles practically all possibilities
- Function call highlighting and matching argument lists
- More accurate defmodule and alias statement rules
- Proper def/defdelegate/defmacro/defguard matching
- Correct scope for symbol names for "Go to Definition"
- LiveView strings
- YAML and JSON strings
- Some keywords are variables depending on the context
- Markdown highlighting within doc comments and also Elixir code examples
- Correct module attribute matching
- Highlight SQL (and jsonb operators) inside the Ecto fragment() function.
- Monokai Theme color scheme rules.
- Better and more organized definition of rules
- Lots of bug fixes

The changes are all in my repo under the rewrite-core branch: https://github.com/azizk/elixir-sublime-syntax/tree/rewrite-core
I can try to rebase onto your main branch, but I don't know how to do that with Github projects yet. We'll see.

Enjoy!

**Comment by azizk** [comment]
I managed to pull the latest commits from my fork and I pushed them to this repo. Now I can delete my fork and continue on your repo directly (still on the rewrite-core branch). Thanks for giving me collab rights!

I'm using my version daily at work. I rarely encounter bugs and overall it's looking pretty good. It will be ready for release soon. I have lots of tests which I need to clean up before I commit them. I'm getting there. :+1:

**Comment by princemaple** [comment]
Cheers! Looking forward to that. Notice I also setup CI for this repo. It automatically runs the syntax tests whenever you push changes. It gives me a basic idea whether it's ready for merge without pulling it down and checking it locally 😄
