### ISSUE TITLE
How to progress with the st3 branch

### ISSUE THREAD

**Issue by azizk** [princemaple/elixir-sublime-syntax#15]
Hey!

So I have some bug fixes that I'd like to commit soon. I was wondering how best to proceed with integrating those into the st3 branch. Is it still okay to rebase the st3 branch as long as it's possible or does that create major issues? As far as I can see the tag(s) have to be set again on the rebased branch. Do you prefer to cherry pick new commits onto the st3 branch?

Happy weekend!

**Comment by princemaple** [comment]
it's best not to rebase st3 branch from now on.

you can
1. branch off master, say branch `A`, finish your work there, push `A`, then
2. send a PR targeting `master`, AND send another PR targeting `st3`, both of them are from `A`. if there are conflicts with `st3`, see (3)
3. on local, checkout `st3`, branch off it, say branch `B`, manually merge your branch `A` into `B`, and push `B`, and send a PR targeting `st3` branch

**Comment by azizk** [comment]
Ok, got it! :+1:
