### ISSUE TITLE
How can we make the package more popular?

### ISSUE THREAD

**Issue by azizk** [princemaple/elixir-sublime-syntax#21]
Hey!

So we probably have the best syntax highlighting definition for Elixir at the moment. The problem is that not many people are installing/updating the package according to [package.io](https://packagecontrol.io/packages/ElixirSyntax).

Of course, we could try and spread the word about it on the different platforms. But I'd like to try something else.

First I'd like to mention this work to José. Maybe he'd be interested in integrating our work into his package. If he isn't, maybe he can at least give it a stamp of approval. Then we can try to get this into [Sublime Text](https://github.com/sublimehq/Packages) itself as an integrated package. That way we would reach the greatest number of developers.

What do you think? Do you have any plans?

**Comment by princemaple** [comment]
Hi,

It's great that now the syntax highlighting is so awesome. It doesn't change the fact that Elixir is still kind of a niche language, though, at the moment. I use it for all my projects, but almost everyone I have met outside immediate Elixir community (e.g. elixir slack, elixir forum, etc) either never heard of Elixir or hadn't tried it. Also, a good portion of Elixir devs are using VS Code.

With that in mind, yes we can try and make it more popular. A mention from José would be great.
A few things to consider: José maintains a package at https://github.com/elixir-editors/elixir-tmbundle
https://github.com/elixir-editors/elixir-tmbundle/pull/135 I once wanted to merge the sublime syntax into it

I'm not sure if elixir will be part of the default packages, but hey the quality is so high now we might as well show them.

I don't really have a plan.

**Comment by azizk** [comment]
You're right that Elixir doesn't enjoy a huge amount of popularity, but it's not doing too shabby for itself. I think there are a lot of companies that adopt it without talking much about it. It's just the language to use if you want OTP and the Beam VM. A good sign is also that there are a considerable amount of job ads out there. That is something that I don't see for the [D](https://dlang.org/) language and they somehow managed to become a default package. In any case, that doesn't have to mean anything to the ST devs and they'll just decide based on their criteria.

Let's see what happens! I'm gonna open an issue on the elixir-tmbundle repo to see what José thinks. :+1:

**Comment by princemaple** [comment]
https://news.ycombinator.com/item?id=27192873

**Comment by azizk** [comment]
Will read! Here is the discussion with José btw: https://github.com/elixir-editors/elixir-tmbundle/issues/188

**Comment by princemaple** [comment]
Yup saw that.

**Comment by princemaple** [comment]
The hacker news link is just for amusement. In case you wonder, I have 0 regrets choosing elixir.

**Comment by princemaple** [comment]
Well, amusement but reflective in terms of how others think. And how elixir will remain a niche for a while.

**Comment by losvedir** [comment]
Holy moly, this syntax is great! I don't know how you make it more popular, but I sure hope you do. I just found it from your issue on the official elixir one. I can finally `F12` to jump to symbols!!! The other syntax seemed to consider call-sites symbols as well, and so you were faced with a useless list when you tried to do that.

**Comment by azizk** [comment]
Thanks! :smile:
Yes, the Goto behaviour was also a pet peeve of mine. Unfortunately it still doesn't work for attribute constants. I think it's a bug in ST, because in Ruby it doesn't work either but it seems to work in other languages.

**Comment by gainhad** [comment]
I also just found this package from the issue on the official repo. Thanks for your work on this!

**Comment by reisub** [comment]
Nice work!
Just a quick suggestion, posting this to https://elixirforum.com/ would probably increase visibility.
I tried to do the same recently, just as an example:
https://elixirforum.com/t/elixirdocs-sublime-text-plugin-for-quick-access-to-hexdocs/41974

**Comment by azizk** [comment]
Thanks @reisub!

Yes, that's my plan after the coming release. :+1:

**Comment by azizk** [comment]
Finally announced on [ElixirForum](https://elixirforum.com/t/elixir-package-for-sublime-text-4/42479) and [Twitter](https://twitter.com/codingaziz/status/1439570753628876803)! :partying_face:

This issue ticket is done in my opinion. :grinning:

**Comment by frou** [comment]
> Yes, the Goto behaviour was also a pet peeve of mine. Unfortunately it still doesn't work for attribute constants. I think it's a bug in ST, because in Ruby it doesn't work either but it seems to work in other languages.

@azizk I'm just passing through, but thought I should mention that that sounds like it's due to the scopes in question falling outside of the whitelists shipped inside ST's `Default` package:

- `Default/Symbol List.tmPreferences`
- `Default/Indexed Symbol List.tmPreferences`
- `Default/Indexed Reference List.tmPreferences`

(You can see the content of those files by using the *View Package File* command in the Command Palette and then searching for those paths)

You can ship your own such files in the Elixir package and hook up additional scopes to be eligible for:

- In-file Goto Definition
- Cross-file Goto Definition
- Cross-file Goto References

...respectively.

More info on that file format here: https://docs.sublimetext.io/reference/symbols.html

**Comment by azizk** [comment]
@frou That's definitely very helpful! Thanks a lot! Gonna add something in the next release to fix this. :+1:
