### ISSUE TITLE
No package description?

### ISSUE THREAD

**Issue by azizk** [princemaple/elixir-sublime-syntax#23]
Hey,

I noticed that ST doesn't display a description for the package in the command palette in contrast to the elixir-tmbundle package. Is it only because I'm overriding with my git repository? On package.io there seems to be a description. It just says "Elixir Sublime Syntax".
![ElixirSyntax_no_description](https://user-images.githubusercontent.com/37282/118889450-6ecb8380-b8fd-11eb-8688-1f962161fab8.png)

Let's find a good one. What do you say? Ideas? :smile:

**Comment by princemaple** [comment]
Installed version does have the description

![image](https://user-images.githubusercontent.com/1329716/118898127-2fc61e00-b94f-11eb-9dec-f08195eb2e15.png)

Although my theme somehow cuts off some text.

**Comment by princemaple** [comment]
"Best Elixir Syntax Highlighting" 🙄

**Comment by princemaple** [comment]
Elixir Syntax definition & First class SublimeText citizen

**Comment by azizk** [comment]
How about "The most powerful Elixir for the most sublime experience." :smile:

**Comment by princemaple** [comment]
Sounds good to me.

**Comment by princemaple** [comment]
Updated repo description. Hopefully it gets picked up by package control soon.

**Comment by princemaple** [comment]
![image](https://user-images.githubusercontent.com/1329716/119246198-e41baa80-bbc2-11eb-87a8-50aa88d994af.png)
it's up

**Comment by azizk** [comment]
Ha! Looking great! :smile:
