### ISSUE TITLE
Elixir code in markdown is only highlighted correctly if started as a module

### ISSUE THREAD

**Issue by princemaple** [princemaple/elixir-sublime-syntax#26]
Should this be considered a bug?
![image](https://user-images.githubusercontent.com/1329716/122842331-86ed5300-d340-11eb-8b86-13129c5a1a0c.png)

**Comment by azizk** [comment]
Not quite. It's more like a limitation than a bug. That was the last thing I was trying to solve before releasing the rewrite. No luck unfortunately. Maybe it's possible with the "lookahead" feature in ST4 but I wouldn't bet on it.

I was thinking about commenting out this feature and documenting it so users can enable it if they so desire. As a side-effect of highlighting code inside Markdown, the functions and modules are offered as Goto-symbols which may be unexpected or undesirable at worst. It's a neat feature but has its issues and maybe it's better to let it go.

**Comment by princemaple** [comment]
Interesting. Thanks for the reply!
