### ISSUE TITLE
Support HEEx/Surface syntax

### ISSUE THREAD

**Issue by azizk** [princemaple/elixir-sublime-syntax#28]
The Surface syntax will be supported in the upcoming v2.2.0 release. See branch: [azizk/add-surface-syntax](/princemaple/elixir-sublime-syntax/tree/azizk/add-surface-syntax)

**Comment by princemaple** [comment]
https://github.com/princemaple/ngx-html-syntax/blob/master/NgxHTML.sublime-syntax

My other syntax project - Angular HTML syntax, which is a superset of HTML. Not sure if this helps. It doesn't have with_prototype.

**Comment by azizk** [comment]
Thanks! I'll take some inspirations. :)

**Comment by cschmatzler** [comment]
I took a shot at this [here](https://github.com/cschmatzler/sublime-surface-syntax) , getting stuck at extending the Elixir syntax due to context limit. Feel free to draw from it and let me know if you need any help!

**Comment by azizk** [comment]
@cschmatzler I updated the syntax file. Would you like to give it a whirl? It's still a WIP.

**Comment by cschmatzler** [comment]
Hey @azizk!

Just got back into office after a long weekend and installed it, looks good at first glance!
I'll ping you or open a PR if I find anything that looks off. 
Thanks for your effort so far!

**Comment by cschmatzler** [comment]
Some small observations so far:

- `<:slot></:slot>` tags are not highlighted.
- On a component, passing `prop={@prop}` is `source.interpolated.elixir.html`, whereas `{=@prop}` is `source.embedded.elixir.html`. Since both have the same semantics, they should probably be highlighted the same.
- Bit of a personal preference, but I prefer having my components highlighted differently than base HTML tags. The VSCode syntax does that by scoping them as `meta.tag.other.unrecognized.html.derivative`. Again, my preference and you can decide how you feel about it.

I am busy with some other stuff that came up, might be able to look into some of this on my own towards the end of the week.

Very good start though!

**Comment by azizk** [comment]
Thanks for the feedback, Christoph. Much appreciated!

**Comment by azizk** [comment]
@cschmatzler Fixed point 1 and 2.

Regarding point 3, I made it so that upper-case tag names get the `entity.tag.name.begin.surface` or `entity.tag.name.end.surface` scope names. You can use those scopes to give them different colours. Do you know if there are any other special Surface tag names? Can they have dots? Can they start with lower-case letters?

**Comment by cschmatzler** [comment]
Hey, thanks for the quick response! Haven't had time to look into it yet because of meetings, but to answer your question: yes, since components are just Elixir modules, they can have dots.

An example from my code would be:
```
<Form for={:product_select_form} change="product_select" submit="product_select">
  <Form.Field name={:index} class="col-span-6 sm:col-span-2 sm:col-start-1">
    <Form.Label>{gettext("Product")}</Form.Label>
    <Form.SelectField selected={@current_product} options={@products} />
  </Form.Field>
</Form>
```

As far as I know, lowercase letters are not permitted in module names.
There's two special Surface components: `<#Markdown>` and `<#Raw>`, the former which pre-compiles Markdown (can we get highlighting to work inside without running into the context limit of Sublime?), the latter which just passes its content to the template without interpolation.

**Comment by cschmatzler** [comment]
Just answered my own question by looking at the definition.

> Commented out because embedding Markdown is too heavy on ST.

It's probably something that can be omitted without too much of an impact, anyways.

**Comment by azizk** [comment]
More fixes and improvements. Does it look like it's done? :crossed_fingers: :smile:

Yeah, the Markdown thing is annoying because the context limit error is ruining the party. Even if the error didn't occur, the next problem would be that the Markdown syntax cannot really be embedded in an indented part of another syntax. Other highlighting issues will occur. ST's regex rule engine matches on each line (where each line start (`^`) is not relative but absolute) and it cannot extract/convert a piece of text – removing indentation/escapes/interpolations/etc. – to use as a new text region for embedded highlighting. Tough problem with no solution in ST. Here is a similar example of Markdown in doc comments:

```elixir
  @moduledoc """
  # A module for `Post` queries.
  """
```
Naturally we'd expect the `#`-line to be highlighted as a first-level header, but it isn't because of the indentation. If you remove the indentation you'll see it highlighted properly. I'm almost curious enough to install VS Code to see how it handles this. :smile:
Afaik, not even that cool [tree-sitter](https://github.com/tree-sitter/tree-sitter) project is capable of handling complex cases like this.

**Comment by cschmatzler** [comment]
That's actually a very interesting limitation, thanks for the lengthy explanation and making me learn something!

Been testing your latest version this morning, can't find anything wrong with it throughout all of my project. 
LGTM?

**Comment by azizk** [comment]
Thanks for the help! Now it's time to polish it and find corner cases. :smiley: :+1:

**Comment by cschmatzler** [comment]
Do you think that `prop` et. al (https://surface-ui.org/components_basics#the-component-api) should be scoped differently because it's not vanilla Elixir or is the current scope of `variable.function.elixir` enough?

**Comment by azizk** [comment]
I think those names aren't rare enough that highlighting them specially wouldn't create false positives. I'm thinking about codebases where these names are used without any relation to Surface. It might only be a minor visual issue if it happens at all, but I'm still not sure if it's a good idea. Maybe it's better if I add a section in the sublime-syntax file so that users can see how to easily customise the style of any function/macro call. :+1:

BTW, do you get any notification without an @-mention when I post here?

**Comment by azizk** [comment]
Hey @cschmatzler!

I'm in the process of finalizing the release. I had to rename the syntax file btw. Hope it didn't cause you too much inconvenience. :grimacing: :slightly_smiling_face:
I also created the HEEx syntax file, enabled the `~H` sigil and improved the `~F` sigil.

Did you notice anything else that I should fix before the release?

**Comment by cschmatzler** [comment]
Hi @azizk!

Sorry that I didn't reply earlier, was on a work break and then came back to a bit of a mess.
Been super happy with the syntax and didn't run into anything that looked off to me, so no blockers from my side.

Having Phoenix 1.6 added is great, too! Thanks so much again for your work on this and making Elixir more accessible to the world ❤️

**Comment by azizk** [comment]
@cschmatzler
No worries! I'm glad you like my work and I'm happy that it works so well.
Yeah, I hope many more people will discover and enjoy this package as time goes on. :+1:
Thanks for your feedback! :heart:

**Comment by princemaple** [comment]
Shall we make a release?

**Comment by azizk** [comment]
@princemaple Not yet, not yet. Gonna clean up and squash the commits. And I need to check if this `apply_prototype` is doing its thing correctly. I don't really see what the difference is compared to `with_prototype`. They practically do the same thing but the latter causes the dreaded context limit error...

**Comment by princemaple** [comment]
😄 OK

**Comment by Rio517** [comment]
For reference, relevant branch: https://github.com/princemaple/elixir-sublime-syntax/tree/azizk/add-surface-syntax

Looking forward to seeing it land! Thanks, guys!

**Comment by azizk** [comment]
It's ready! :partying_face:

@princemaple It's probably midnight at your end right now. Maybe you're not too tired for the update. I can wait of course. :)
I'd like to announce the release on my twitter account and on the Elixir forum. So I'll do it whenever you get to updating the package. :+1:

@Rio517 Thanks for the tip!

PS: some unimportant syntax tests fail because new syntax scopes are being used even though I didn't bump ST's version. There were many updates on the built-in syntax files, but a new version of ST isn't even available yet... :thinking: Will fix that later.

**Comment by princemaple** [comment]
@azizk you can make the announcement now if you are still awake... Keep in mind that it will take another few hours before Package Control picks it up though. Sorry to keep you waiting.

**Comment by princemaple** [comment]
AU timezone is really awkward. 8+ hours diff with most EU countries. 7-10 hours diff with U.S. cities.

**Comment by azizk** [comment]
No problem at all @princemaple! Thanks for releasing as soon as you could! :ok_hand:

Yeah, the timezone is a bit inconvenient, but come to think of it: together we can provide support 24/7 for this project. :rofl:

**Comment by cschmatzler** [comment]
Works great! Thanks for releasing this, @azizk and @princemaple!
