### ISSUE TITLE
moduledoc code block

### ISSUE THREAD

**Issue by princemaple** [princemaple/elixir-sublime-syntax#29]
![image](https://user-images.githubusercontent.com/1329716/126943389-e9786cda-b164-47f0-b26e-0fbbb7dbfe9e.png)

https://github.com/swoosh/swoosh/blob/main/lib/swoosh/mailer.ex#L81

First red `_measurement` has this scope

```
source.elixir
meta.function-call.arguments.elixir
meta.block.elixir
meta.doc.elixir
source.markdown.embedded.elixir
meta.string.elixir
markup.list.unnumbered.markdown
meta.paragraph.list.markdown
markup.italic.markdown
```

**Comment by azizk** [comment]
That's strange. In my editor it looks fine. The underscore in Markdown is for making text italic, right? But in my editor it's just a code block. Nothing is red.

**Comment by princemaple** [comment]
It's there to mark the variable as unused.

**Comment by princemaple** [comment]
The other blocks in the front display fine. Even when I add underscore prefixed variable.

![image](https://user-images.githubusercontent.com/1329716/126949926-5af4a16c-26e5-4715-8ef5-676e7489511e.png)

**Comment by princemaple** [comment]
I copied the whole module to a few blocks above, it displayed fine. *Scratching my head*

**Comment by princemaple** [comment]
![image](https://user-images.githubusercontent.com/1329716/126950664-1291a9d0-3213-4a6e-8e0b-d03a143d2b53.png)

For some reason the list above never ended and is causing everything below it to have the unnumbered list scope. Weird.

Probably not an issue in this repo?

**Comment by azizk** [comment]
Could be a Markdown syntax highlighter issue? But it's still weird that I couldn't reproduce the problem.

**Comment by princemaple** [comment]
Do you have relevant changes in 2.2?

**Comment by azizk** [comment]
Yeah maybe :-) I'll check later again.

**Comment by azizk** [comment]
Played around with it a bit. When I indent the events list above the errors disappear. :man_shrugging:

In some way it has to do with our package. It uses Markdown to highlight the doc comments, but the Markdown package was not really designed to be embedded inside a heredoc string of another language.

**Comment by princemaple** [comment]
I guess we can't do much about it either way 😹
