### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by woylie** [princemaple/elixir-sublime-syntax#30]
I tried installing ElixirSyntax, but when I open an .ex file, I'm getting this error:

> Error loading syntax file "Packages/ElixirSyntax/syntaxes/Elixir.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

![image](https://user-images.githubusercontent.com/13847569/129134541-68742104-684f-4ada-b770-5786b87c011b.png)

Sublime Text 4 build 4113
macOS Big Sur 11.5.1
ElixirSyntax 2.1.0

**Comment by princemaple** [comment]
Thank for reporting. Is it possible to include your file that triggered the issue? Or an equivalent snippet.

This is kind of known issue. If you could also give this branch a go and let us know whether your problem persists, it would be very appreicated! https://github.com/princemaple/elixir-sublime-syntax/tree/azizk/add-surface-syntax

**Comment by woylie** [comment]
The error occurs with every file I opened. In the linked branch it works, though.

**Comment by princemaple** [comment]
Great. We just need to wait for green light from @azizk for release then.

**Comment by princemaple** [comment]
I'll leave this open. @azizk please let me know when 2.2 is ready to go :) then I will make a release and close this one.

Thanks for the quick responses @woylie !

**Comment by woylie** [comment]
I'm not sure. I just tried it on another Macbook, same problem.

**Comment by princemaple** [comment]
Could be this? https://github.com/princemaple/elixir-sublime-syntax/commit/43192fc7b8b839aa585706b7f755cb0f74ee33d6

Are they EEx files?

**Comment by woylie** [comment]
No, that were just regular .ex files.

**Comment by princemaple** [comment]
v2.2.0 is out. Hopefully Package Control picks it up in the next couple hours.
